### ISSUE TITLE
Number Parsing truncate decimals

### ISSUE THREAD

**Issue by cKuppel** [bijukunjummen/aws-sdk2-dynamo-json-helper#2]
https://github.com/bijukunjummen/aws-sdk2-dynamo-json-helper/blob/ff2b93bd7cd75b41c39087fb417ec84f6c2faa9b/src/main/java/org/bk/aws/dynamo/util/JsonAttributeValueUtil.java#L84

It appears that the parsing for a decimal value truncate the number.

**:bug: Reproduction details**
 - input string : `"1.5"`
 - expected output : `1.5`
 - actual output : `1`
 - jdk terumin 17.0.6

Behind the scene, the `Number.getInstance().parse("3.5")` 

The workaround to fix that behaviour is to get `org.apache.commons.lang3.math.NumberUtils`

`Number number = NumberUtils.createNumber(attributeValue.n());`

**Comment by bijukunjummen** [comment]
Ooh, thanks @cKuppel, will plan to fix it.

**Comment by bijukunjummen** [comment]
Merged your additional test @cKuppel , looks like it is working as expected with the numeric types?
